// SPDX-License-Identifier: GPL-2.0-or-later

#define EXFAT_BASE_VERSION	"5.8"
#define EXFAT_EXTRAVERSION	"1"
#define EXFAT_VARIANT		"arter97"
#define EXFAT_VERSION		EXFAT_BASE_VERSION "-" EXFAT_EXTRAVERSION EXFAT_VARIANT
